# Generated by Django 5.1.4 on 2024-12-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='specify',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images_menu/'),
        ),
    ]
